### ISSUE TITLE
gotoDate do not work for resourceDay, resourceWeek, resourceNextWeeks

### ISSUE THREAD

**Issue by FHenry** [jarnokurlin/fullcalendar#16]
but it works for resourceMonth.
Similar issie was already exists : #12 
The fix is the same :
remove date = new Date();
 in calss ResourceNextWeeksView, ResourceWeekView, ResourceDayView function render into else case

**Comment by wbercx** [comment]
I found this out today as well.

**Comment by FHenry** [comment]
If you apply the pull request
https://github.com/jarnokurlin/fullcalendar/pull/17/files
You will solve this problem

**Comment by FHenry** [comment]
since 2014 it may be not accurate
